theme: jekyll-theme-slate
title : FoolCoin
tagline: "Blockchain FoolCoin"
description: >
  Blockchain Fortune Telling, Counting Your "Foolishness" <br/>
  区块链算命，测算您的『愚气』

production_url : http://foolcoin.one
